apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
        - name: registration-app
          image: 222093271/registration-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_TYPE
              value: "mongodb"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-uri-secret
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              value: "registerdb"
            - name: DEBUG
              value: "false"
          # <-- Health checks start here -->
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  type: NodePort
  selector:
    app: registration-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
